export type { ChannelAdapter, ChannelHost, InboundMessage } from "./types"
export { ChannelRouter } from "./router"
export { TelegramAdapter, type TelegramConfig } from "./telegram"
export { GitLabAdapter, type GitLabConfig } from "./gitlab"
export { WhatsAppAdapter, type WhatsAppConfig } from "./whatsapp"
export { GitHubAdapter, type GitHubConfig } from "./github"
